Repository sunxysharma/webrtc-application, pull requests merged in 2020-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: Hacktoberfest, documentation

#6 footer-addded
  public/index.html
Labels: hacktoberfest-accepted

#7 Update Readme.md
  README.md
Labels: hacktoberfest-accepted

#8 footer changes
  README.md
  public/index.html
Labels: good first issue, hacktoberfest-accepted

#9 login page
  .gitignore
  CONTRIBUTING.md
  LICENSE
  README.md
  package.json
  public/img/doge.png
  public/index.html
  public/pages/login-page.html
  public/scripts/index.js
  public/styles.css
  src/index.ts
  src/server.ts
  tsconfig.json
Labels: hacktoberfest-accepted

#10 register form
  public/pages/login-page.html
Labels: hacktoberfest-accepted

#11 about-us-page
  public/pages/about-us.html
Labels: hacktoberfest-accepted
